ViewComponentsExample/Models/Person.cs
namespace ViewComponentswithViewDataCoreMVC6.Models
{
  public class Person
  {
    public string? PersonName { get; set; }
    public string? JobTitle { get; set; }
  }
}

ViewComponentsExample/Models/PersonGridModel.cs
namespace ViewComponentswithViewDataCoreMVC6.Models
{
  public class PersonGridModel
  {
    public string GridTitle { get; set; } = string.Empty;
    public List<Person> Persons { get; set; } = new List<Person>();
  }
}

ViewComponentsExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ViewComponentswithViewDataCoreMVC6.Controllers
{
  public class HomeController : Controller
  {
    [Route("/")]
    public IActionResult Index()
    {
      return View();
    }

    [Route("about")]
    public IActionResult About()
    {
      return View();
    }
  }
}

ViewComponentsExample/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using ViewComponentswithViewDataCoreMVC6.Models;

namespace ViewComponentswithViewDataCoreMVC6.ViewComponents
{
  public class GridViewComponent : ViewComponent
  {
    public async Task<IViewComponentResult> InvokeAsync()
    {
      PersonGridModel model = new PersonGridModel()
      {
        GridTitle = "Persons List",
        Persons = new List<Person>() {
          new Person() { PersonName = "John", JobTitle = "Manager" },
          new Person() { PersonName = "Jones", JobTitle = "Asst. Manager" },
          new Person() { PersonName = "William", JobTitle = "Clerk" },
        }
      };
      ViewData["Grid"] = model;
      return View("Sample"); //invoked a partial view Views/Shared/Components/Grid/Default.cshtml
    }
  }
}

ViewComponentsExample/Views/Home/About.cshtml
@{
 ViewBag.Title = "About";
}

<h1>About</h1>
<p>Demonstration of View Components with View Data in Asp.Net Core MVC 6</p>
@await Component.InvokeAsync("Grid")

<vc:grid></vc:grid>

ViewComponentsExample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h1>Home</h1>
@await Component.InvokeAsync("Grid")

ViewComponentsExample/Views/Shared/Components/Grid/Sample.cshtml
<div class="box">
 <h3>@ViewBag.Grid.GridTitle</h3>
 <table class="table w-100">
  <thead>
   <tr>
    <th>Sl. No</th>
    <th>Name</th>
   </tr>
  </thead>
  <tbody>
   @foreach (Person person in ViewBag.Grid.Persons)
   {
    <tr>
     <td>@person.PersonName</td>
     <td>@person.JobTitle</td>
    </tr>
   }
  </tbody>
 </table>

</div>

ViewComponentsExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
 <meta name="viewport" content="width=device-width" />
 <title>@ViewBag.Title</title>
 <link href="~/StyleSheet.css" rel="stylesheet" />
</head>
<body>
 <div class="container">
  <div class="navbar">
            <div class="navbar-brand">Demonstration of View Components with View Data in Asp.Net Core MVC 6 </div>
   <ul>
    <li><a href="~/">Home</a></li>
    <li><a href="~/about">About</a></li>
   </ul>
  </div>

  <div class="page-content">
   @RenderBody()
  </div>
 </div>
</body>
</html>